### ISSUE TITLE
The Quantum Computer Heat Value doesn't update when off

### ISSUE THREAD

**Issue by Prometheus0000** [Technus/TecTech#33]
#### Which modpack version are you using?
GTNH 2.0.9.0 QF3
TecTech-1.7.10-3.8.3

#
#### What did you try to do, and what did you expect to happen?
Try to find out how long until the heat goes away.
#
#### What happened instead? (Attach screenshots if needed)
Value in controller doesn't change until you turn it on again.

You can check the heat % by using the portable scanner on each individual computer rack, but it would be better if this number updated in the controller when off so I could tell when it's finished cooling off, or how much it's reduced, or how fast it's reducing. Also, it says Current max. Heat? The max is constantly increasing? Shouldn't max be removed? Or two values, one for max that doesn't change, and one for current that does. But as I understand it the circuits and racks can have different values, so that number would probably need to be on the rack itself. So I guess it's an average, but the number in the interface is only useful when it's on.

Also, the racks' interface just has the heat icon lit up, not an indication of how much it's heated up, or how much until it blows up (does that happen?) or the circuit is destroyed. It should probably also say on the rack that you can't remove the stuff on a tooltip for the heat icon, as well as current heat, and whether it's increasing or decreasing.
#
#### What do you suggest instead/what changes do you propose?
See above

**Comment by Technus** [comment]
Added refreshing of temp when controller is off. https://github.com/Technus/TecTech/commit/2ad9e1927127ee115741ebed7c24de617e0df1b9
Also this should be done via Scanner, since how it is supposed to work without power on?

Current max temp is the only necessary number you need anyway. It is just the max heat value of rack hatches, since yes all of them have their own value. If you need more info on single one just scan them.
